/**
 * AUTO-GENERATED — do not edit by hand.
 *
 * Generated by `openapi-typescript` from apps/api/openapi.json.
 * This placeholder is committed so the web app typechecks before the api's
 * OpenAPI spec is first emitted. Run `pnpm --filter @mango/shared types:gen`
 * (after `pnpm --filter api openapi`) to replace it with the real contract.
 */

export interface paths {}
export interface webhooks {}
export interface components {
  schemas: Record<string, never>;
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type operations = Record<string, never>;
