/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: operations["AppController_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/upload-contract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload a PDF, create a Setu signature request, and persist the metadata */
        post: operations["EsignController_uploadContract"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/signature-status/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch the latest status from Setu, persist it, and return the record */
        get: operations["EsignController_getStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/download/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream the signed PDF back through the backend */
        get: operations["EsignController_download"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/webhooks/setu": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Receive Setu eSign status notifications (HMAC-verified) */
        post: operations["SetuWebhookController_receive"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorBodyDto: {
            /**
             * @description Stable SCREAMING_SNAKE error code
             * @example NOT_FOUND
             */
            code: string;
            /** @example Signature request not found */
            message: string;
            /** @description Optional structured detail (e.g. field validation errors) */
            details?: {
                [key: string]: unknown;
            };
        };
        ErrorResponseDto: {
            error: components["schemas"]["ErrorBodyDto"];
        };
        SignatureDetailsDto: {
            /** @example AARAV SHARMA */
            aadhaarName?: string;
            /** @example 4821 */
            aadhaarSuffix?: string;
            /** @example 1994 */
            birthYear?: string;
            /** @example M */
            gender?: string;
            /** @example 560001 */
            postalCode?: string;
        };
        SignatureRecordDto: {
            /** @example req_9f3k2m8q4x7c */
            id: string;
            /** @example doc_1a2b3c4d5e6f */
            documentId: string;
            /** @example sig_1a2b3c4d5e6f */
            signatureId: string;
            /** @example nda-acme.pdf */
            fileName: string;
            /** @example Mutual NDA — Acme Corp */
            documentName: string | null;
            /** @example Aarav Sharma */
            signerName: string;
            /** @example aarav@example.com */
            signerIdentifier: string;
            /**
             * @example sign_pending
             * @enum {string}
             */
            status: "sign_initiated" | "sign_pending" | "sign_in_progress" | "sign_complete";
            /**
             * @example pending
             * @enum {string}
             */
            signerStatus: "pending" | "in_progress" | "signed";
            /** @description Hosted Setu signing URL */
            signerUrl: string;
            signatureDetails: components["schemas"]["SignatureDetailsDto"] | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        SetuWebhookDto: {
            /** @example ESIGN_WEBHOOK_NOTIFICATION */
            event: string;
            /** @example 2026-07-06T12:00:00.000Z */
            timeStamp: string;
            /**
             * @example {
             *       "esign": {
             *         "id": "sig_123",
             *         "documentId": "doc_123",
             *         "status": "sign_complete",
             *         "signers": []
             *       }
             *     }
             */
            data: {
                [key: string]: unknown;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EsignController_uploadContract: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /**
                     * Format: binary
                     * @description PDF (≤10MB)
                     */
                    file: string;
                    /** @example Aarav Sharma */
                    signerName: string;
                    /** @example aarav@example.com */
                    signerIdentifier: string;
                    /** @example 1994 */
                    birthYear?: string;
                    /** @example Mutual NDA */
                    documentName?: string;
                    /** @example http://localhost:3000/signing-complete */
                    redirectUrl: string;
                };
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignatureRecordDto"];
                };
            };
        };
    };
    EsignController_getStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignatureRecordDto"];
                };
            };
        };
    };
    EsignController_download: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The signed PDF */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/pdf": unknown;
                };
            };
        };
    };
    SetuWebhookController_receive: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetuWebhookDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
